#!/usr/bin/env bun
// Fetch OpenFlights airports.dat, filter to commercial airports with valid IATA + IANA tz,
// emit SQL to db/init/04-airports-seed.sql.
//
// Re-run when OpenFlights updates (check https://openflights.org/data.html):
//   bun run db/seeds/generate-airports.ts
//
// Then apply to a live DB via:
//   ./scripts/load-airports.sh

import { writeFileSync } from "node:fs";
import { join } from "node:path";

const SOURCE = "https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat";
const OUT = join(import.meta.dir, "../init/04-airports-seed.sql");

// OpenFlights CSV: every field is either a quoted string or unquoted number. No embedded
// commas inside strings appear in practice — a simple split-on-`","` with trim works,
// but we parse more carefully to be safe.
function parseCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (c === '"') { inQuotes = !inQuotes; continue; }
    if (c === "," && !inQuotes) { out.push(cur); cur = ""; continue; }
    cur += c;
  }
  out.push(cur);
  return out;
}

function sqlEscape(s: string): string {
  return s.replace(/'/g, "''");
}

const TZ_RE = /^[A-Za-z_0-9+-]+(\/[A-Za-z_0-9+-]+)*$/;
const IATA_RE = /^[A-Z]{3}$/;

console.error(`Fetching ${SOURCE}...`);
const resp = await fetch(SOURCE);
if (!resp.ok) {
  console.error(`Failed: HTTP ${resp.status}`);
  process.exit(1);
}
const text = await resp.text();
const lines = text.split(/\r?\n/).filter(Boolean);
console.error(`Got ${lines.length} rows`);

interface Airport { iata: string; name: string; city: string; country: string; tz: string }
const airports: Airport[] = [];
let skipped = { no_iata: 0, bad_tz: 0, bad_iata: 0 };

for (const line of lines) {
  const cols = parseCsvLine(line);
  if (cols.length < 12) continue;
  const name = cols[1]?.trim();
  const city = cols[2]?.trim();
  const country = cols[3]?.trim();
  const iata = cols[4]?.trim();
  const tz = cols[11]?.trim();

  if (!iata || iata === "\\N" || iata === "") { skipped.no_iata++; continue; }
  if (!IATA_RE.test(iata)) { skipped.bad_iata++; continue; }
  if (!tz || tz === "\\N" || tz === "") { skipped.bad_tz++; continue; }
  if (!TZ_RE.test(tz)) { skipped.bad_tz++; continue; }

  airports.push({ iata, name, city, country, tz });
}

// Dedupe on IATA (OpenFlights occasionally has duplicates; keep first)
const seen = new Set<string>();
const deduped = airports.filter(a => {
  if (seen.has(a.iata)) return false;
  seen.add(a.iata);
  return true;
});

console.error(
  `Kept ${deduped.length} airports (skipped: no IATA=${skipped.no_iata}, bad IATA=${skipped.bad_iata}, bad tz=${skipped.bad_tz}, dupes=${airports.length - deduped.length})`,
);

// Emit SQL. Multi-row INSERT with ON CONFLICT DO UPDATE → idempotent re-runs.
const header = `-- Auto-generated by db/seeds/generate-airports.ts
-- Source: ${SOURCE}
-- Generated: ${new Date().toISOString()}
-- Airports: ${deduped.length}

\\connect travel

`;

const CHUNK = 500;
const chunks: string[] = [];
for (let i = 0; i < deduped.length; i += CHUNK) {
  const batch = deduped.slice(i, i + CHUNK);
  const values = batch
    .map(a => `  ('${sqlEscape(a.iata)}', '${sqlEscape(a.name)}', '${sqlEscape(a.city)}', '${sqlEscape(a.country)}', '${sqlEscape(a.tz)}')`)
    .join(",\n");
  chunks.push(
    `insert into public.airports (iata, name, city, country, tz) values\n${values}\non conflict (iata) do update set\n  name = excluded.name,\n  city = excluded.city,\n  country = excluded.country,\n  tz = excluded.tz;\n`,
  );
}

writeFileSync(OUT, header + chunks.join("\n"), "utf8");
console.error(`Wrote ${OUT}`);
